### ISSUE TITLE
tag 7.6.3 points to 7.5.1 in setup.py

### ISSUE THREAD

**Issue by lorenzncode** [CadQuery/OCP-stubs#1]
It looks like the recent CadQuery PR tests are failing due to setup.py pointing to 7.5.1 in tag 7.6.3.

https://github.com/CadQuery/cadquery/blob/03c3266b8d61d487349a15f73d3b3cb13bce625f/appveyor.yml#L31

https://github.com/CadQuery/OCP-stubs/blob/24323f86ff87ac82902ef6ad34123b051bf207b1/setup.py#L7

Log for CadQuery/cadquery#1176
https://ci.appveyor.com/project/jmwright/cadquery-o18bh/builds/45477612/job/n1hds7hef1n6pvn5

**Comment by lorenzncode** [comment]
Sorry, this is not really the root cause of the cadquery mypy failure.   The version labeling mismatch confused me.  It looks like the mypy check fails now with mypy version 0.991.

**Comment by adam-urbanczyk** [comment]
Indeed 991 has a breaking change, see here https://mypy-lang.blogspot.com/2022/11/mypy-0990-released.html

**Comment by lorenzncode** [comment]
Thanks, closing.   I see the setup.py version is not very important.  Perhaps in a future update the setup.py version, and tag, can both be synced with the corresponding OCP/OCCT version.
